export * from './adminHunts.service';
import { AdminHuntsService } from './adminHunts.service';
export * from './adminUsers.service';
import { AdminUsersService } from './adminUsers.service';
export * from './alert.service';
import { AlertService } from './alert.service';
export * from './category.service';
import { CategoryService } from './category.service';
export * from './chats.service';
import { ChatsService } from './chats.service';
export * from './contacts.service';
import { ContactsService } from './contacts.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './geofence.service';
import { GeofenceService } from './geofence.service';
export * from './hunts.service';
import { HuntsService } from './hunts.service';
export * from './identities.service';
import { IdentitiesService } from './identities.service';
export * from './promotion.service';
import { PromotionService } from './promotion.service';
export * from './subscription.service';
import { SubscriptionService } from './subscription.service';
export * from './template.service';
import { TemplateService } from './template.service';
export * from './tokens.service';
import { TokensService } from './tokens.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AdminHuntsService, AdminUsersService, AlertService, CategoryService, ChatsService, ContactsService, DashboardService, GeofenceService, HuntsService, IdentitiesService, PromotionService, SubscriptionService, TemplateService, TokensService, UsersService];
