/**
 * OutOut API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HuntGoalReachedResponseDto } from './huntGoalReachedResponseDto';


export interface HuntResponseDto { 
    id?: number;
    name?: string | null;
    city?: string | null;
    cityPart?: string | null;
    startAt?: string;
    endAt?: string;
    totalGoals?: number;
    reachedGoals?: Array<HuntGoalReachedResponseDto> | null;
}

