/**
 * OutOut API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GenderType } from './genderType';


export interface InlineObject6 { 
    id?: number | null;
    name?: string | null;
    phoneNumber?: string | null;
    email?: string | null;
    dateOfBirth?: string | null;
    genderType?: GenderType;
    profileImage?: Blob | null;
    categories?: Array<number> | null;
    companyName?: string | null;
    phoneNumberVerificationCode?: string | null;
}

