/**
 * OutOut API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoCoordinate } from './geoCoordinate';


export interface NewChatMessageDto { 
    chatId?: number;
    content?: string | null;
    promotionId?: number | null;
    urls?: Array<string> | null;
    geoCoordinate?: GeoCoordinate;
}

