/**
 * OutOut API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PromotionStatusEnum = 1 | 2 | 3 | 4;

export const PromotionStatusEnum = {
    Scheduled: 1 as PromotionStatusEnum,
    Live: 2 as PromotionStatusEnum,
    Expired: 3 as PromotionStatusEnum,
    Disabled: 4 as PromotionStatusEnum
};

