/**
 * OutOut API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StringPagedRequest { 
    includes?: string | null;
    pageSize?: number;
    page?: number;
    fromId?: number | null;
    updatedAfter?: string | null;
    orderByKey?: string | null;
    isDescending?: boolean;
    isFullSize?: boolean;
    query?: string | null;
    filter?: string | null;
}

