/**
 * OutOut API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRoleEnum } from './userRoleEnum';
import { SubscriptionResponseDto } from './subscriptionResponseDto';
import { GenderType } from './genderType';


export interface UserResponseDto { 
    id?: number;
    name?: string | null;
    phoneNumber?: string | null;
    companyName?: string | null;
    email?: string | null;
    dateOfBirth?: string | null;
    genderType?: GenderType;
    role?: UserRoleEnum;
    profileImage?: string | null;
    createdOn?: string | null;
    phoneNumberVerifiedAt?: string | null;
    emailVerifiedAt?: string | null;
    reciveOffers?: boolean;
    categories?: Array<string> | null;
    hasBeenSubscribed?: boolean;
    activeSubscriptions?: Array<SubscriptionResponseDto> | null;
}

